services:
  db:
    image: postgres:17.5
    container_name: restrequests_db
    restart: always
    environment:
      POSTGRES_DB: ${DATASOURCE_DB}
      POSTGRES_USER: ${DATASOURCE_USERNAME}
      POSTGRES_PASSWORD: ${DATASOURCE_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  flyway:
    image: flyway/flyway:11.0
    command: >
      -url=${SPRING_FLYWAY_URL}
      -user=${DATASOURCE_USERNAME}
      -password=${DATASOURCE_PASSWORD}
      -schemas=public
      -locations=filesystem:/flyway/sql
      migrate
    volumes:
      - ./src/main/resources/db/migration:/flyway/sql
    depends_on:
      - db

  app:
    build:
      context: .
      dockerfile: deployment/Dockerfile
    container_name: rest_requestform
    restart: always
    depends_on:
      - db
      - flyway
    env_file: .env
    ports:
      - "8082:8080"

volumes:
  postgres_data:
