server:
  port: 8080
spring:
  application:
    name: "RestApiRequest"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
  jwt:
    secret: "4749f898-788d-4be2-bae3-819980ac5f03"
    expiration: 900000
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"
logging:
  level:
    org.springframework.r2dbc: DEBUG
    io.r2dbc.postgresql: DEBUG
adapters:
  r2dbc:
    host: "localhost"
    port: 5432
    database: "PragmaDB"
    schema: "public"
    username: "postgres"
    password: "p*5tgr35q1"
